default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  database: colombo_production
  username: colombo
  password: <%= ENV['COLOMBO_DATABASE_PASSWORD'] %>
