default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['COLOMBO_DATABASE_USERNAME'] %>
  password: <%= ENV['COLOMBO_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: colombo_development

test:
  <<: *default
  database: colombo_test

production:
  <<: *default
  database: colombo_production

